import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const {
      name,
      surname,
      institution,
      delegationSize,
      phone,
      email,
      position,
      role,
    } = body;

    // Validate required fields
    if (
      !name ||
      !surname ||
      !institution ||
      !delegationSize ||
      !phone ||
      !email ||
      !position ||
      !role
    ) {
      return NextResponse.json(
        { error: 'All form fields are required.' },
        { status: 400 }
      );
    }

    const emailUser = process.env.EMAIL_USER;
    const emailPass = process.env.EMAIL_PASS;

    if (!emailUser || !emailPass) {
      console.warn(
        '[OXCMUN Apply API]: EMAIL_USER or EMAIL_PASS environment variables are not configured.'
      );
      return NextResponse.json(
        { error: 'Email service configuration missing on server.' },
        { status: 500 }
      );
    }

    // Configure Nodemailer SMTP Transporter
    const transporter = nodemailer.createTransport({
      service: 'gmail',
      auth: {
        user: emailUser,
        pass: emailPass,
      },
    });

    // Clean HTML email template
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <style>
            body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; background-color: #f4f6f9; margin: 0; padding: 20px; color: #1e293b; }
            .container { max-width: 650px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.08); border: 1px solid #e2e8f0; }
            .header { background: #0f172a; padding: 24px 30px; text-align: center; border-bottom: 4px solid #D9278E; }
            .header h1 { color: #ffffff; margin: 0; font-size: 20px; letter-spacing: 1px; font-weight: 700; text-transform: uppercase; }
            .header p { color: #94a3b8; margin: 6px 0 0 0; font-size: 13px; }
            .content { padding: 30px; }
            .badge { display: inline-block; background-color: #fce7f3; color: #be185d; padding: 6px 14px; border-radius: 20px; font-size: 12px; font-weight: 700; text-transform: uppercase; margin-bottom: 20px; }
            .table-container { width: 100%; border-collapse: collapse; margin-top: 15px; }
            .table-container th, .table-container td { padding: 14px 16px; border-bottom: 1px solid #edf2f7; text-align: left; font-size: 14px; }
            .table-container th { background-color: #f8fafc; color: #475569; font-weight: 600; width: 40%; }
            .table-container td { color: #0f172a; font-weight: 500; }
            .footer { background-color: #f8fafc; padding: 18px 30px; text-align: center; border-top: 1px solid #e2e8f0; color: #64748b; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="container">
            <div class="header">
              <h1>OXCMUN ANKARA PREMUN</h1>
              <p>New Student Application Received</p>
            </div>
            <div class="content">
              <div class="badge">Role: ${role}</div>
              <table class="table-container">
                <tr>
                  <th>First Name</th>
                  <td>${name}</td>
                </tr>
                <tr>
                  <th>Last Name</th>
                  <td>${surname}</td>
                </tr>
                <tr>
                  <th>Institution</th>
                  <td>${institution}</td>
                </tr>
                <tr>
                  <th>Delegation Size</th>
                  <td>${delegationSize}</td>
                </tr>
                <tr>
                  <th>Phone Number</th>
                  <td><a href="tel:${phone}" style="color: #2563eb; text-decoration: none;">${phone}</a></td>
                </tr>
                <tr>
                  <th>Email Account</th>
                  <td><a href="mailto:${email}" style="color: #2563eb; text-decoration: none;">${email}</a></td>
                </tr>
                <tr>
                  <th>Position</th>
                  <td>${position}</td>
                </tr>
                <tr>
                  <th>Role Selected</th>
                  <td><strong>${role}</strong></td>
                </tr>
              </table>
            </div>
            <div class="footer">
              <p>This message was automatically generated by the OXCMUN Registration System.</p>
            </div>
          </div>
        </body>
      </html>
    `;

    const mailOptions = {
      from: `"OXCMUN Registration Portal" <${emailUser}>`,
      to: emailUser,
      replyTo: email,
      subject: `[OXCMUN PREMUN Application] - ${name} ${surname} (${institution})`,
      html: htmlContent,
    };

    await transporter.sendMail(mailOptions);

    return NextResponse.json(
      {
        success: true,
        message: 'Your application has been received successfully.',
      },
      { status: 200 }
    );
  } catch (error) {
    console.error('[OXCMUN Apply API Error]:', error);
    return NextResponse.json(
      { error: 'Failed to send application email. Please try again later.' },
      { status: 500 }
    );
  }
}
